version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_HOST=${HOSTNAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://${HOSTNAME}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_data:/files
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role != manager
      restart_policy:
        condition: on-failure
      labels:
      - traefik.enable=true
      - traefik.swarm.network=traefik-public
      - traefik.http.routers.n8n.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.n8n.entrypoints=http
      - traefik.http.services.n8n.loadbalancer.server.port=5678

volumes:
  n8n_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,nfsvers=4"
      device: ":/mnt/ext1/docker/n8n"

networks:
  traefik-public:
    external: true